name: Health check

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-20.04
    steps:
    - name: Perform a health check
      uses: jtalk/url-health-check-action@v3
      with:
        url: https://pokedex-cicd.fly.dev
