name: Health check

on:
  push:
    branches:
      - master

jobs:
  test_schedule:
    runs-on: ubuntu-20.04
    steps:
    - name: Perform a health check
      uses: jtalk/url-health-check-action@v3
      with:
        url: https://pokedex-cicd.fly.dev
